package proyecto1;
import proyecto1.Lexer;
import java_cup.runtime.*;
import java.util.*;


// Código del parser
parser code{:
    Lexer lexer;
    @SuppressWarnings("deprecation")
    public parser(Lexer lexer){
        this.lexer = lexer; 
        this.symbolFactory = new DefaultSymbolFactory();
    }

    public boolean syntaxErrors;
    public void syntax_error(Symbol current_token) {
        System.err.println("Syntax error at line " + (current_token.left + 1) +
            ", column " + (current_token.right + 1) +
            ": unexpected token \"" + current_token.value + "\"");
        syntaxErrors = true; // Marcar que ocurrió un error
    }

    String tac = "";
    int tempCount = 0;
    int labelCount = 0;
    boolean commentTac = true;

    String currentSwitchExpression = "";
    String currentSwitchLabel = "";

    private String getCurrentSwitchExpression() {
        return currentSwitchExpression;
    }
    private void setCurrentSwitchExpression(String expression) {
        currentSwitchExpression = expression;
    }
    private String getCurrentSwitchLabel() {
        return currentSwitchLabel;
    }
    private void setCurrentSwitchLabel(String label) {
        currentSwitchLabel = label;
    }
    private void cleanCurrentSwitchExpression() {
        currentSwitchExpression = "";
    }
    private void cleancurrentSwitchLabel() {
        currentSwitchLabel = "";
    }

    Stack<String> stackStartLabels = new Stack<String>();
    Stack<String> stackEndLabels = new Stack<String>();

    private String newLabel() {
        return "L" + (labelCount++);
    }
    private String newTemp() {
        return "t" + (tempCount++);
    }

    private void emit(String text) {
        tac += text + "\n";
    }
    private String evaluateComparator(String e1, String comparator, String e2) {
        //System.out.println("E1: " + e1 + "Op:"+ comparator+" E2: " + e2);
        if (e1 == null || e2 == null) 
            throw new IllegalArgumentException("Cannot compare null values");
        String temp = newTemp();
        switch (comparator) {
            case "==":
                emit(temp + "=" + e1 + "==" + e2);
                return temp;
            case "!=":
                emit(temp + "=" + e1 + "!=" + e2);
                return temp;
            case "<":
                emit(temp + "=" + e1 + "<" + e2);
                return temp;
            case ">":
                emit(temp + "=" + e1 + ">" + e2);
                return temp;
            case "<=":
                emit(temp + "=" + e1 + "<=" + e2);
                return temp;
            case ">=":
                emit(temp + "=" + e1 + ">=" + e2);
                return temp;
            default:
                throw new IllegalArgumentException("Unknown comparator: " + comparator);
        }
    }
    private String evaluateArithmetic(String e1, String operator, String e2) {
        //System.out.println("E1: " + e1 + "Op:"+ operator+" E2: " + e2);
        if (e1 == null || e2 == null) 
            throw new IllegalArgumentException("Cannot perform arithmetic operations with null values");
        //if (commentTac) emit("// Performing " + e1 + " " + operator + " " + e2);
        if (e1.matches("[a-zA-Z]+")) {
            String temp = newTemp();
            emit(temp + "=" + e1);
            e1 = temp;
        }
        if (e2.matches("[a-zA-Z]+")) {
            String temp = newTemp();
            emit(temp + "=" + e2);
            e2 = temp;
        }
        String temp = newTemp();
        switch (operator) {
            case "+":
                emit(temp + "=" + e1 + "+" + e2);
                return temp;
            case "-":
                emit(temp + "=" + e1 + "-" + e2);
                return temp;
            case "*":
                emit(temp + "=" + e1 + "*" + e2);
                return temp;
            case "/":
                emit(temp + "=" + e1 + "/" + e2);
                return temp;
            case "%":
                emit(temp + "=" + e1 + "%" + e2);
                return temp;
            case "^":
                emit(temp + "=" + e1 + "^" + e2);
                return temp;
            default:
                throw new IllegalArgumentException("Unknown arithmetic operator: " + operator);
        }
    }
    // Método auxiliar para obtener el tipo
    private String getType(String expression) {
        //System.out.println("Expression: " + expression);
        return expression.split(":")[0];
    }
    private String getValue(String expression) {
        //System.out.println("Expression: " + expression);
        return expression.toString().split(":")[1];
    }
    
    
:}

init with {::};

scan with {: Symbol sym = lexer.next_token();
            //System.out.println("Token procesado: " + sym); // Imprime el token procesado
            return sym;:}

// Terminales
terminal INTEGER, BOOLEAN, CHAR, STRING, FLOAT;
terminal LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET, ASSIGNMENT, LEFT_PARENTHESIS, RIGHT_PARENTHESIS;
terminal ADD, SUB, MUL, DIV, MOD, TO_THE_POWER;
terminal INCREMENT, DECREMENT;
terminal LESS_THAN, LESS_OR_EQUAL_THAN, GREATER_THAN, GREATER_OR_EQUAL_THAN, EQUAL_TO, NOT_EQUAL_TO;
terminal AND, OR, NOT;
terminal SEMICOLON, COLON, IF, ELSE, WHILE, FOR, SWITCH, CASE, DEFAULT, BREAK, RETURN;
terminal PRINT, INPUT;
terminal MAIN;
terminal ID, INTEGER_VAL, FLOAT_VAL, BOOL_VAL, CHAR_VAL, STRING_VAL;
terminal COMMA;


// No terminales
non terminal program, code_block, main;
non terminal comparator, arithmetic_operator;
non terminal for, for_initialization, while, if, switch, single_case, cases, read, print, return;
non terminal statement, expression, unary_operation;
non terminal type;
non terminal declaration, variable_declaration, function_declaration;
non terminal function_call, parameters, arguments;
non terminal array_declaration, array_access, array_values;
non terminal block;
non terminal literal, value_assignment, array_position_assignment, array_declaration_aux;
non terminal case1, case2, switch_aux, program_aux;

precedence left OR;       // Disyunción tiene menor precedencia
precedence left AND;      // Conjunción tiene mayor precedencia que OR
precedence right NOT;     // NOT tiene la mayor precedencia
precedence left EQUAL_TO, NOT_EQUAL_TO;
precedence left LESS_THAN, LESS_OR_EQUAL_THAN, GREATER_THAN, GREATER_OR_EQUAL_THAN;
precedence left ADD, SUB;
precedence left MUL, DIV, MOD;
precedence right TO_THE_POWER;  // Precedencia más alta para potenciación
precedence right INCREMENT, DECREMENT, NOT;  // Precedencia para unarios
precedence right LEFT_PARENTHESIS;

start with program;

type ::= INTEGER:tipo {:RESULT = "int"; :} // Cargar tipos unicamente
       | BOOLEAN:tipo {:RESULT = "bool"; :}
       | CHAR:tipo {:RESULT = "char"; :}
       | STRING:tipo {:RESULT = "string"; :}
       | FLOAT:tipo {:RESULT = "float"; :};


unary_operation ::= ID:id INCREMENT 
                    {: 
                        Simbolo simbolo = TablaSimbolos.buscar(id.toString());
                        if (simbolo == null) 
                            throw new IllegalArgumentException("ID " + id.toString() + " not found.");
                        if (simbolo.getValue() == null)
                            throw new IllegalArgumentException("ID " + id.toString() + " is empty. Value needed for unary operation.");
                        if (!(simbolo.type.equals("int"))) 
                            throw new IllegalArgumentException("ID " + id.toString() + " is not an integer. Unary operation only allowed for integers.");
                        RESULT = "int:"+id.toString()+":"+id.toString()+":+";
                    :}
                  | ID:id DECREMENT 
                    {: 
                        Simbolo simbolo = TablaSimbolos.buscar(id.toString());
                        if (simbolo == null) 
                            throw new IllegalArgumentException("ID " + id.toString() + " not found.");
                        if (simbolo.getValue() == null) 
                            throw new IllegalArgumentException("ID " + id.toString() + " is empty. Value needed for unary operation.");
                        try {
                            Integer.parseInt(simbolo.getValue());
                        } catch (Exception e) {
                            throw new IllegalArgumentException("ID " + id.toString() + " is not an integer. Unary operation only allowed for integers.");
                        }
                        RESULT = "int:"+id.toString()+":"+id.toString()+":-";
                    :};

arithmetic_operator ::= ADD {:RESULT = "+"; :}
    | SUB {:RESULT = "-"; :}
    | MUL {:RESULT = "*"; :}
    | DIV {:RESULT = "/"; :}
    | MOD {:RESULT = "%"; :}
    | TO_THE_POWER {:RESULT = "^"; :};

comparator ::= LESS_THAN {:RESULT = "<"; :}
             | LESS_OR_EQUAL_THAN {:RESULT = "<="; :}
             | GREATER_THAN {:RESULT = ">"; :}
             | GREATER_OR_EQUAL_THAN {:RESULT = ">="; :}
             | EQUAL_TO {:RESULT = "=="; :}
             | NOT_EQUAL_TO {:RESULT = "!="; :}; 
literal ::= ID:id {:
            Simbolo simbolo = TablaSimbolos.buscar(id.toString());
            if (simbolo == null) 
                throw new IllegalArgumentException("ID " + id.toString() + " not found. Here"); 
            RESULT = simbolo.type.toString() + ":" + id.toString(); :}
            | INTEGER_VAL:i {:RESULT = "int:" + i.toString();:}
            | FLOAT_VAL:f {:RESULT = "float:" + f.toString();:}
            | BOOL_VAL:b {:RESULT = "bool:" + b.toString();:}
            | CHAR_VAL:c {:RESULT = "char:" + c.toString();:}
            | STRING_VAL:s {:RESULT = "string:" + s.toString();:};
// Reglas de la gramática
expression ::= literal:i {:RESULT = i.toString();:}
            | LEFT_PARENTHESIS expression:e RIGHT_PARENTHESIS {:RESULT = e.toString();:}
            | expression:e1 arithmetic_operator:o expression:e2 {:
            if (commentTac) emit("// Performing " + e1.toString() + " " + o.toString() + " " + e2.toString());
            String e1Type = getType(e1.toString());
            String e2Type = getType(e2.toString());
            if (e1Type.equals("int") && e2Type.equals("int")) 
                RESULT = "int:"+evaluateArithmetic(getValue(e1.toString()), o.toString(), getValue(e2.toString()));
            else if (e1Type.equals("float") && e2Type.equals("float"))
                RESULT = "float:"+evaluateArithmetic(getValue(e1.toString()), o.toString(), getValue(e2.toString())); 
            else 
                throw new IllegalArgumentException("Incompatible types for arithmetic operations, only integer-integer and float-float are allowed.");
            :}
            | unary_operation:o {:
                String[] parts = o.toString().split(":");
                String id = parts[1];
                String operation = parts[3];
                if (operation.equals("+")) {
                    if (commentTac) emit("Incrementing " + id + " by 1");
                    String temp1 = newTemp();
                    emit(temp1 + "=1");
                    String temp2 = newTemp();
                    emit(temp2 + "=" + id + "+" + temp1);
                    emit(id + "=" + temp2);
                } else {
                    if (commentTac) emit("Decrementing " + id + " by 1");
                    String temp1 = newTemp();
                    emit(temp1 + "=1");
                    String temp2 = newTemp();
                    emit(temp2 + "=" + id + "-" + temp1);
                    emit(id + "=" + temp2);
                }
            RESULT = o.toString();:}
            | function_call:f {:RESULT = f.toString();:}
            | expression:e1 comparator:c expression:e2 {: 
                if (commentTac) emit("// Comparing " + e1.toString() + " " + c.toString() + " " + e2.toString());
                String e1Type = getType(e1.toString());
                String e2Type = getType(e2.toString());
                if ((e1Type.equals("int") && e2Type.equals("int") || (e1Type.equals("float") && e2Type.equals("float")))) 
                    RESULT = "bool:"+evaluateComparator(getValue(e1.toString()), c.toString(), getValue(e2.toString())); 
                else 
                    throw new IllegalArgumentException("Incompatible types for comparison operations, only integer-integer and float-float are allowed.");
            :}
            | expression:e1 AND expression:e2 {:
                if (commentTac) emit("// Performing " + e1.toString() + " AND " + e2.toString());
                String e1Type = getType(e1.toString());
                String e2Type = getType(e2.toString());
                if (e1Type.equals("bool") && e2Type.equals("bool")) {
                    String temp = newTemp();
                    emit(temp + "=" + getValue(e1.toString()) + "&&" + getValue(e2.toString()));
                    RESULT = "bool:" + temp;
                } else {
                    throw new IllegalArgumentException("Incompatible types for AND operation, only boolean-boolean is allowed.");
                }
            :}
            | expression:e1 OR expression:e2 {:
                if (commentTac) emit("// Performing " + e1.toString() + " OR " + e2.toString());
                String e1Type = getType(e1.toString());
                String e2Type = getType(e2.toString());
                if (e1Type.equals("bool") && e2Type.equals("bool")) {
                    String temp = newTemp();
                    emit(temp + "=" + getValue(e1.toString()) + "||" + getValue(e2.toString()));
                    RESULT = "bool:" + temp;
                } else {
                    throw new IllegalArgumentException("Incompatible types for OR operation, only boolean-boolean is allowed.");
                }
            :}
            | NOT expression:e {:
                if (commentTac) emit("// Performing NOT " + e.toString());
                String eType = getType(e.toString());
                if (eType.equals("bool")) {
                    String temp = newTemp(); 
                    emit(temp + "=!" + getValue(e.toString()));
                    RESULT = "bool:" + temp;
                } else {
                    throw new IllegalArgumentException("Incompatible type for NOT operation, only boolean is allowed.");
                }
            :};

statement ::= for // Ya
            | while // Ya
            | if // Ya
            | switch // Ya
            | declaration // Ya
            | read // Ya
            | print // Ya 
            | return // Ya
            | function_call SEMICOLON // Ya
            | unary_operation:o {: // Ya
                String[] parts = o.toString().split(":");
                String id = parts[1];
                String operation = parts[3];
                if (operation.equals("+")) {
                    if (commentTac) emit("// Incrementing " + id + " by 1");
                    String temp1 = newTemp();
                    emit(temp1 + "=1");
                    String temp2 = newTemp();
                    emit(temp2 + "=" + id + "+" + temp1);
                    emit(id + "=" + temp2);
                } else {
                    if (commentTac) emit("// Decrementing " + id + " by 1");
                    String temp1 = newTemp();
                    emit(temp1 + "=1");
                    String temp2 = newTemp();
                    emit(temp2 + "=" + id + "-" + temp1);
                    emit(id + "=" + temp2);
                }
            RESULT = o.toString();:} SEMICOLON // Ya
            | array_declaration // Ya
            | array_access SEMICOLON // Ya
            | value_assignment // Ya
            | array_position_assignment SEMICOLON // Ya
            | block
            | error SEMICOLON;

block ::= LEFT_BRACE {:TablaSimbolos.abrirScope();:} code_block RIGHT_BRACE {:TablaSimbolos.cerrarScope();:}
             |error RIGHT_BRACE ;
code_block ::= statement
             | expression
             | statement code_block
             | expression code_block;

declaration ::= variable_declaration:type 
              | function_declaration:type ;

//Crear entrada de variable
value_assignment ::= ID:id ASSIGNMENT expression:e SEMICOLON {:
                        Simbolo simbolo = TablaSimbolos.buscar(id.toString());
                        if (simbolo == null) 
                            System.err.println("ID " + id.toString() + " not found.");
                        if (!simbolo.type.equals(getType(e.toString())))
                            throw new IllegalArgumentException("ID " + id.toString() + " is not of type " + getType(e.toString()) + ". Value assigned has to be of the same type.");
                        simbolo.setValue(getValue(e.toString()));
                        emit(id.toString() + "=" + getValue(e.toString()));
                    :};
variable_declaration ::= type:typeVar ID:idVar SEMICOLON {:
                        if (commentTac) emit("// Variable " + idVar.toString() + " declaration");
                        Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                        TablaSimbolos.agregarSimbolo(simbolo);
                        emit(typeVar.toString() + ":" +idVar.toString());
                        RESULT=""+typeVar.toString()+":"+idVar.toString();:}
                        | type:typeVar ID:idVar ASSIGNMENT expression:e SEMICOLON {:
                            if (commentTac) emit("// Variable " + idVar.toString() + " declaration with value");
                          Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                          simbolo.setValue(getValue(e.toString()));
                          TablaSimbolos.agregarSimbolo(simbolo);
                          emit(typeVar.toString() + ":" +idVar.toString() + "=" + getValue(e.toString()));
                            RESULT=""+typeVar.toString()+":"+idVar.toString();:};

//Crear entrada de función
function_declaration ::= type:typeVar ID:idVar LEFT_PARENTHESIS parameters:p RIGHT_PARENTHESIS LEFT_BRACE 
                        {:
                            if (commentTac) emit("// Function " + idVar.toString() + " declaration");
                            Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                            simbolo.setFunction(typeVar.toString(), TablaSimbolos.getParametrosEnEspera());
                            TablaSimbolos.limpiarParametrosEnEspera();
                            TablaSimbolos.agregarSimbolo(simbolo);
                            String functionLabel = idVar.toString();
                            emit(functionLabel + ":");
                            String[] parameters = p.toString().split(",");
                            try {
                                for (String parameter: parameters) {
                                    emit (getValue(parameter) + "=pop");
                                }
                            } catch (Exception e) {
                                //throw new IllegalArgumentException("Error while processing function parameters.");
                            }


                        :} 
                        code_block RIGHT_BRACE;

parameters ::= type:typeVar ID:idVar {:
                Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                TablaSimbolos.agregarParametroEnEspera(simbolo);
                TablaSimbolos.agregarSimbolo(simbolo);
                RESULT = typeVar.toString() + ":" + idVar.toString();
            :}//Entrada de parametros
             | type:typeVar ID:idVar COMMA parameters:p{:
                Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                TablaSimbolos.agregarParametroEnEspera(simbolo);
                TablaSimbolos.agregarSimbolo(simbolo);
                RESULT = typeVar.toString() + ":" + idVar.toString() + "," + p.toString();
            :}| {:RESULT="";:};

function_call ::= ID:id LEFT_PARENTHESIS arguments:args RIGHT_PARENTHESIS 
                  {: 
                    if (commentTac) emit("// Calling function " + id.toString() + " with arguments " + args.toString() + "--------------");
                    Simbolo simbolo = TablaSimbolos.buscar(id.toString());
                    if (simbolo == null) 
                        throw new IllegalArgumentException("ID " + id.toString() + " not found.");
                    if (!simbolo.isFunction())
                        throw new IllegalArgumentException("ID " + id.toString() + " is not a function.");
                    int arguments = args.toString().isEmpty() ? 0 : args.toString().split(",").length;
                    if (arguments != simbolo.getParameters().size())
                        throw new IllegalArgumentException("Function " + id.toString() + " expects " + simbolo.getParameters().size() + " arguments, but " + args.toString().split(",").length + " were provided.");
                    String temp = newTemp(); 
                    emit("call " + id.toString());
                    emit(temp + "=$ret"); 
                    RESULT = simbolo.returnType+":"+temp; 
                  :};

arguments ::= expression:e {:
            emit("push " + e.toString());
            RESULT=e;:}
            | expression:e COMMA arguments:a {:
            emit("push " + e.toString());
            RESULT = e.toString() + "," + a.toString();
            :}| {:RESULT = "";:};

return ::= RETURN expression:e SEMICOLON {:emit("return "+e.toString());:}
         | RETURN SEMICOLON {:emit("return");:};

read ::= INPUT LEFT_PARENTHESIS ID:id RIGHT_PARENTHESIS SEMICOLON 
    {: 
        if (commentTac) emit("// Read statement");
        Simbolo simbolo = TablaSimbolos.buscar(id.toString());
        if (simbolo == null) 
            throw new IllegalArgumentException("ID " + id.toString() + " not found.");
        String type = simbolo.type;
        if (!type.equals("string"))
            throw new IllegalArgumentException("ID " + id.toString() + " is not a string. Variable destination has to be of value string.");
        String temp = newTemp(); 
        emit("read " + temp);
        emit(id.toString() + "=" + temp);  
        RESULT = "string:"+id.toString();
    :};

print ::= PRINT LEFT_PARENTHESIS expression:e RIGHT_PARENTHESIS SEMICOLON 
    {: 
        if (commentTac) emit("// Print statement");
        String type = getType(e.toString());
        if (!type.equals("string") && !type.equals("int") && !type.equals("float"))
            throw new IllegalArgumentException("Only string, int and float values are allowed for print.");
        String temp = newTemp();
        emit(temp + "=" + getValue(e.toString()));
        emit("push " + temp);
        emit("print"); 
    :};

if ::= IF LEFT_PARENTHESIS expression:e RIGHT_PARENTHESIS {:
        if (commentTac) emit("// If statement ---------------");
        String tipo = getType(e.toString());
        if (!tipo.equals("bool"))
            throw new IllegalArgumentException("Expression has to be of type boolean.");
        String endLabel = newLabel();
        String elseLabel = newLabel();
        stackEndLabels.push(endLabel);
        stackEndLabels.push(elseLabel);
        emit("ifFalse " + getValue(e.toString()) + " goto " + elseLabel);
    :} block ELSE {:
        String elseLabel = stackEndLabels.pop();
        String endLabel = stackEndLabels.pop();
        emit("goto " + endLabel);
        emit(elseLabel + ":");
        stackEndLabels.push(endLabel);
    :} block {:
        String endLabel = stackEndLabels.pop();
        emit(endLabel + ":");
    :}; 

for_initialization ::= type:typeVar ID:idVar ASSIGNMENT expression:e
                     {:
                                Simbolo simbolo = new Simbolo(idVar.toString(),typeVar.toString(),idVarleft,idVarright);
                                TablaSimbolos.agregarSimbolo(simbolo);
                                simbolo.setValue(getValue(e.toString()));
                                emit(typeVar.toString() + ":" + idVar.toString() + "=" + getValue(e.toString()));
                    :};

for ::= {:if (commentTac) emit("// For loop --------------");:} 
        FOR LEFT_PARENTHESIS for_initialization SEMICOLON expression:e SEMICOLON unary_operation:u RIGHT_PARENTHESIS {:
        String tipo = getType(e.toString());
        System.out.println("Tipo: " + tipo);
        if (!tipo.equals("bool"))
            throw new IllegalArgumentException("Expression in for has to be of type boolean.");
        String endLabel = newLabel();
        String startLabel = newLabel();
        stackStartLabels.push(startLabel);
        stackEndLabels.push(endLabel);
        emit(startLabel + ":");
        emit("ifFalse " + getValue(e.toString()) + " goto " + endLabel); :}
        block {:
            String startLabel = stackStartLabels.pop();
            String endLabel = stackEndLabels.pop();
            String[] partsUnaryOperation = u.toString().split(":");
            String id = partsUnaryOperation[2];
            String operation = partsUnaryOperation[3];
            String temp1 = newTemp();
            emit(temp1 + "=1");
            String temp2 = newTemp();
            if (operation.equals("+")) 
                emit(temp2 + "=" + id + "+" + temp1);
            else 
                emit(temp2 + "=" + id + "-" + temp1);
            emit(id + "=" + temp2);
            emit("goto " + startLabel);
            emit(endLabel + ":");
        :};

while ::= WHILE LEFT_PARENTHESIS expression:e RIGHT_PARENTHESIS
          {: 
            if (commentTac) emit("// While loop ---------------");
            Simbolo expression = TablaSimbolos.buscar(getValue(e.toString()));
            if (!expression.getType().equals("bool"))
                throw new IllegalArgumentException("Expression has to be of type boolean.");
            if (expression == null) 
                throw new IllegalArgumentException("Expression not found.");
            String startLabel = newLabel();
            String endLabel = newLabel();
            emit(startLabel + ":");
            emit("ifFalse " + getValue(e.toString()) + " goto " + endLabel);
            stackStartLabels.push(startLabel);
            stackEndLabels.push(endLabel);
            :} 
          block 
          {: 
            String endLabel = stackEndLabels.pop();
            String startLabel = stackStartLabels.pop();

            emit("goto " + startLabel);
            emit(endLabel + ":");
          :};

case1 ::= CASE expression:e COLON {:
    String label = getCurrentSwitchLabel();
    String expressionType = getType(e.toString());
    String switchExpression = getCurrentSwitchExpression();
    if (!expressionType.equals(getType(switchExpression)))
        throw new IllegalArgumentException("Case expression has to be of the same type as the switch expression.");
    String temp = newTemp();
    setCurrentSwitchLabel(newLabel());
    emit(label + ":");
    emit("ifFalse " + getValue(e.toString()) + "==" + getValue(getCurrentSwitchExpression()) + " goto " + currentSwitchLabel);
:} code_block BREAK {: 
    String endLabel = stackEndLabels.peek();
    emit("goto " + endLabel);
:} SEMICOLON {:RESULT = e.toString();:};


single_case ::= case1:c {:RESULT = c.toString();:} ;

cases ::= single_case cases
        | single_case;

switch_aux ::= SWITCH LEFT_PARENTHESIS expression:e RIGHT_PARENTHESIS 
           LEFT_BRACE 
           {: 
               if (commentTac) emit("// Switch statement -----------------");
               TablaSimbolos.abrirScope(); 
               String endLabel = newLabel(); 
               stackEndLabels.push(endLabel);
               setCurrentSwitchExpression(e.toString()); 
               setCurrentSwitchLabel(newLabel()); 
           :} 
           cases;
switch ::= switch_aux RIGHT_BRACE 
           {: TablaSimbolos.cerrarScope(); String endLabel = stackEndLabels.pop(); emit(endLabel + ":"); :}
           | switch_aux DEFAULT COLON {:emit(currentSwitchLabel + ":");:} code_block RIGHT_BRACE 
           {: TablaSimbolos.cerrarScope(); String endLabel = stackEndLabels.pop(); emit(endLabel + ":"); :};

array_declaration_aux ::=
type:t 
{:
    if (!t.toString().equals("int") && !t.toString().equals("char")) 
         throw new IllegalArgumentException("Only int and char arrays are allowed.");
:}
LEFT_BRACKET expression:s {:
    String size = s.toString();
    if (!getType(size).equals("int"))
        throw new IllegalArgumentException("Array size has to be an integer."); 
    :} RIGHT_BRACKET ID:id {:
        Simbolo simboloBuscar = TablaSimbolos.buscar(id.toString());
        if (simboloBuscar != null) 
            throw new IllegalArgumentException("ID " + id.toString() + " already exists.");
        Simbolo simbolo = new Simbolo(id.toString(), t.toString(), idleft, idright);
        System.out.println("sim: "+simbolo);
        simbolo.setArray();
        TablaSimbolos.agregarSimbolo(simbolo);
        RESULT = t.toString() + ":" + id.toString();
        emit("" + t.toString() + ":" + id.toString() + "=newArray " + getValue(s.toString()));
    :};
array_declaration ::= array_declaration_aux:t ASSIGNMENT LEFT_BRACE array_values:v {:
     String[] values = v.toString().split(",");
     int i = 0;
     Simbolo simbolo = TablaSimbolos.buscar(t.toString().split(":")[1]);  
     simbolo.setArraySize(values.length);
     for (String value: values) {
         if (!getType(value).equals(getType(t.toString())))
            throw new IllegalArgumentException("Array values have to be of the same type as the array.");
            emit(values[1] + "[" + i + "]=" + getValue(value));
            i++;
     }
    :} RIGHT_BRACE SEMICOLON 
    | array_declaration_aux SEMICOLON;

array_values ::=  expression:e {:RESULT=e;:} | expression:e COMMA array_values:values {:RESULT=e.toString()+","+values.toString();:};

array_access ::= ID:id LEFT_BRACKET expression:e {:
    String type = getType(e.toString());
    if (!type.equals("int"))
        throw new IllegalArgumentException("Array access index has to be an integer.");
    Simbolo simbolo = TablaSimbolos.buscar(id.toString());
    if (simbolo == null) 
        throw new IllegalArgumentException("ID " + id.toString() + " array not found.");
    if (!simbolo.isArray())
        throw new IllegalArgumentException("ID " + id.toString() + " is not an array.");
    String temp = newTemp();
    emit(temp + "=" + id.toString() + "[" + getValue(e.toString()) + "]");
    RESULT = simbolo.type + ":" + temp;
:} RIGHT_BRACKET; //{: System.out.println("Se acceso a un array"); :};

array_position_assignment ::= array_access ASSIGNMENT expression:e {:RESULT=e.toString();:};


main ::= MAIN LEFT_PARENTHESIS RIGHT_PARENTHESIS block;

program ::= program_aux;

program_aux ::= function_declaration program_aux
            | main {:System.out.println(tac);:}; 