
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOT_EQUAL_TO = 25;
  public static final int INCREMENT = 18;
  public static final int CHAR = 4;
  public static final int ASSIGNMENT = 9;
  public static final int INPUT = 41;
  public static final int CASE = 36;
  public static final int INTEGER = 2;
  public static final int TO_THE_POWER = 17;
  public static final int GREATER_OR_EQUAL_THAN = 23;
  public static final int FOR = 34;
  public static final int DECREMENT = 19;
  public static final int GREATER_THAN = 22;
  public static final int NOT = 28;
  public static final int SEMICOLON = 29;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int COMMA = 49;
  public static final int BOOL_VAL = 46;
  public static final int LEFT_BRACE = 7;
  public static final int DIV = 15;
  public static final int RIGHT_PARENTHESIS = 11;
  public static final int MAIN = 42;
  public static final int IF = 31;
  public static final int ID = 43;
  public static final int STRING_VAL = 48;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 39;
  public static final int LESS_OR_EQUAL_THAN = 21;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int FLOAT_VAL = 45;
  public static final int CHAR_VAL = 47;
  public static final int ADD = 12;
  public static final int RIGHT_BRACE = 8;
  public static final int MOD = 16;
  public static final int BREAK = 38;
  public static final int EQUAL_TO = 24;
  public static final int INTEGER_VAL = 44;
  public static final int SWITCH = 35;
  public static final int COLON = 30;
  public static final int ELSE = 32;
  public static final int WHILE = 33;
  public static final int DEFAULT = 37;
  public static final int FLOAT = 6;
  public static final int STRING = 5;
  public static final int LESS_THAN = 20;
  public static final int SUB = 13;
  public static final int PRINT = 40;
  public static final int LEFT_PARENTHESIS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "FLOAT",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "ASSIGNMENT",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "MOD",
  "TO_THE_POWER",
  "INCREMENT",
  "DECREMENT",
  "LESS_THAN",
  "LESS_OR_EQUAL_THAN",
  "GREATER_THAN",
  "GREATER_OR_EQUAL_THAN",
  "EQUAL_TO",
  "NOT_EQUAL_TO",
  "AND",
  "OR",
  "NOT",
  "SEMICOLON",
  "COLON",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "PRINT",
  "INPUT",
  "MAIN",
  "ID",
  "INTEGER_VAL",
  "FLOAT_VAL",
  "BOOL_VAL",
  "CHAR_VAL",
  "STRING_VAL",
  "COMMA"
  };
}

